=== bigbluebutton/bigbluebutton/bigbluebutton-server/src/org/red5/io/flv/impl/FLVMetaData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/FLVMetaData" xmlns:tns="http://www.example.org/FLVMetaData">
	<element name="flashvideo">
		<annotation>
			<documentation>Root element</documentation>
		</annotation>
		<complexType>
			<sequence>
			
				<element name="file" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="name" type="string"></element>
							<element name="size" type="string"></element>
							<element name="modified" type="string">
							</element>
							<element name="meta" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="position"
											type="string">
										</element>
										<element name="timestamp"
											type="string">
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== bigbluebutton/bigbluebutton/bigbluebutton-server/bin/org/red5/io/flv/impl/FLVMetaData_Template.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:flashvideo xmlns:tns="http://www.example.org/FLVMetaData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/FLVMetaData FLVMetaData.xsd ">
  <file>
  	<name>
  		FLV File One
  	</name>
  	<size>
  		333333333333
  	</size>
  	<modified>
  		modified time
  	</modified>
    <meta>
      <position>Position1</position>
      <timestamp>TimeStamp1</timestamp>
    </meta>
    <meta>
      <position>Position2</position>
      <timestamp>TimeStamp2</timestamp>
    </meta>
    <meta>
      <position>Position3</position>
      <timestamp>TimeStamp3</timestamp>
    </meta>
    <meta>
      <position>Position4</position>
      <timestamp>TimeStamp4</timestamp>
    </meta>
    <meta>
      <position>Position5</position>
      <timestamp>TimeStamp5</timestamp>
    </meta>
  </file>
  <file>
  	<name>
  		FLV File Two
  	</name>
  	<size>
  		333333333333333
  	</size>
  	<modified>
  		modified time
  	</modified>
    <meta>
      <position>Position</position>
      <timestamp>TimeStamp</timestamp>
    </meta>
  </file>
</tns:flashvideo>
